# -*- coding: utf-8 -*-
"""trabalho_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kiZU0ZMre7D-lSKYhEdAtcc3vjKu_7D2
"""

"""
================================================================================
PROJETO 2 — DISCIPLINA DE SÉRIES TEMPORAIS (ME607)
================================================================================

TÍTULO: Modelagem da Volatilidade e Análise de Intervenção em Retornos da
        Petrobras (PETR4): Impactos de Eventos Político-Econômicos
        no Período 2010–2026

AUTOR:  Arthur Narcizo
DATA:   30/04/2026

================================================================================
INSTRUÇÕES DE USO
================================================================================

PASSO 1 — INSTALAR AS DEPENDÊNCIAS
   Abra o terminal  e execute o seguinte comando único de instalação:

   pip install pandas numpy matplotlib seaborn statsmodels arch scipy

PASSO 2 — EXECUTAR O SCRIPT
   No mesmo terminal, na pasta onde se encontra este arquivo, execute:

       python trabalho_2.py

PASSO 3 — VERIFICAR AS SAÍDAS
   Após a execução, duas pastas serão criadas no diretório do script:

   ./figuras/        → 6 gráficos em PNG (figura 01 a 06)
   ./resultados/     → tabelas (CSV) e sumários (TXT) com todos os
                       resultados estatísticos citados no relatório

OBSERVAÇÕES:
   • Todos os resultados numéricos do relatório são reproduzíveis
     (semente aleatória fixada em 42).
   • Os dados utilizados estão hospedados em:
     https://github.com/arthurnarcizo/S-ries_Temporais_ME607

================================================================================
"""

# ==============================================================================
# IMPORTAÇÃO DAS BIBLIOTECAS
# ==============================================================================

import os                                              # criação de pastas
import warnings                                        # silenciar avisos
import numpy as np                                     # álgebra numérica
import pandas as pd                                    # manipulação de dados
import matplotlib.pyplot as plt                        # gráficos
import seaborn as sns                                  # gráficos estatísticos
from scipy import stats                                # testes e distribuições
from statsmodels.tsa.stattools import adfuller, kpss   # estacionariedade
from statsmodels.stats.diagnostic import acorr_ljungbox, het_arch  # resíduos
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf       # ACF/PACF
from arch import arch_model                            # modelos GARCH

# Configurações globais
warnings.filterwarnings("ignore")     # suprime warnings de convergência
np.random.seed(42)                     # reprodutibilidade
sns.set_style("whitegrid")             # estilo dos gráficos

# Cria as pastas de saída (caso ainda não existam)
os.makedirs("figuras",   exist_ok=True)
os.makedirs("resultados", exist_ok=True)


# ==============================================================================
# 1. COLETA DE DADOS — DIRETO DO GITHUB
# ==============================================================================
# Os dados são lidos diretamente do repositório público
# ==============================================================================

URL_DADOS = ("https://raw.githubusercontent.com/arthurnarcizo/"
             "S-ries_Temporais_ME607/refs/heads/main/trabalho_2_data.csv")

print("=" * 70)
print("1. COLETA DE DADOS — PETR4 (via GitHub)")
print("=" * 70)

# Lê o CSV do GitHub: a primeira coluna é a data (índice)
petr = pd.read_csv(URL_DADOS, index_col=0, parse_dates=True)

print("\nColunas encontradas no arquivo:", list(petr.columns))
print("Primeiras 3 linhas:")
print(petr.head(3))

# Detecta automaticamente a coluna de preço (compatibilidade com Yahoo Finance)
if "Close" in petr.columns:
    preco = petr["Close"]
elif "Adj Close" in petr.columns:
    preco = petr["Adj Close"]
else:
    preco = petr.iloc[:, 0]

# Limpeza: garante numérico, remove NaN, ordena cronologicamente
preco = pd.to_numeric(preco, errors='coerce').dropna()
preco.index = pd.to_datetime(preco.index)
preco = preco.sort_index()

# Filtra a janela de análise definida no relatório
preco = preco.loc["2010-01-01":"2026-04-30"]

# Calcula os LOG-RETORNOS em percentual:
# Justificativa teórica: Morettin (2017), cap. 1 — retornos compostos têm
# propriedades estatísticas mais adequadas (aditividade temporal).
retorno = 100 * np.log(preco / preco.shift(1)).dropna()
retorno.name = "PETR4"

print(f"\nPeríodo:                {preco.index.min().date()} a {preco.index.max().date()}")
print(f"Observações de preço:   {len(preco)}")
print(f"Observações de retorno: {len(retorno)}")


# ==============================================================================
# 2. EVENTOS POLÍTICO-ECONÔMICOS PARA ANÁLISE DE INTERVENÇÃO
# ==============================================================================
# Eventos selecionados pela literatura e por reportagens da imprensa
# financeira como pontos de quebra estrutural significativa em PETR4.
# Referência metodológica: Box & Tiao (1975).
# ==============================================================================

eventos = {
    "Lava Jato (início)":              "2014-03-17",
    "Saída de Pedro Parente":          "2018-05-31",
    "Demissão Castello Branco":        "2021-02-19",
    "Mudança política preços (Lula)":  "2023-03-08",
    "Demissão Jean Paul Prates":       "2024-05-14",
}


# ==============================================================================
# 3. ANÁLISE DESCRITIVA E EXPLORATÓRIA
# ==============================================================================

print("\n" + "=" * 70)
print("3. ANÁLISE DESCRITIVA")
print("=" * 70)

# --- Estatísticas resumo dos log-retornos ---
desc = pd.Series({
    "N":                  len(retorno),
    "Média":              retorno.mean(),
    "Mediana":            retorno.median(),
    "Desvio-padrão":      retorno.std(),
    "Mínimo":             retorno.min(),
    "Máximo":             retorno.max(),
    "Assimetria":         retorno.skew(),
    "Curtose (excesso)":  retorno.kurtosis(),
})
print(desc.round(4))
desc.to_csv("resultados/descritivas.csv")

# --- FIGURA 01: série de preços + log-retornos com eventos ---
fig, axes = plt.subplots(2, 1, figsize=(14, 8))
axes[0].plot(preco, color='steelblue', linewidth=0.8)
axes[0].set_title("PETR4 — Preço de Fechamento Ajustado", fontsize=12)
axes[0].set_ylabel("Preço (R$)")
for nome, data in eventos.items():
    axes[0].axvline(pd.to_datetime(data), color='red',
                    linestyle='--', alpha=0.6, linewidth=1)
    axes[0].annotate(nome, xy=(pd.to_datetime(data), preco.max() * 0.92),
                     rotation=90, fontsize=8, color='darkred', ha='right')

axes[1].plot(retorno, color='steelblue', linewidth=0.5, alpha=0.8)
axes[1].set_title("PETR4 — Log-retornos diários (%)", fontsize=12)
axes[1].set_ylabel("Retorno (%)")
axes[1].axhline(0, color='black', linewidth=0.5)
for data in eventos.values():
    axes[1].axvline(pd.to_datetime(data), color='red',
                    linestyle='--', alpha=0.5, linewidth=1)
plt.tight_layout()
plt.savefig("figuras/01_serie_eventos.png", dpi=130)
plt.close()

# --- FIGURA 02: distribuição dos retornos vs Normal ---
fig, axes = plt.subplots(1, 2, figsize=(13, 5))
sns.histplot(retorno, kde=True, stat='density', bins=80,
             ax=axes[0], color='steelblue')
xx = np.linspace(retorno.min(), retorno.max(), 500)
axes[0].plot(xx, stats.norm.pdf(xx, retorno.mean(), retorno.std()),
             'r-', label='Normal teórica', linewidth=2)
axes[0].set_title("Histograma vs. Normal — caudas pesadas evidentes")
axes[0].legend()
stats.probplot(retorno, dist="norm", plot=axes[1])
axes[1].set_title("QQ-plot vs. Normal")
plt.tight_layout()
plt.savefig("figuras/02_distribuicao.png", dpi=130)
plt.close()

# --- Testes estatísticos ---
# Cada teste responde uma pergunta diferente:
#   Jarque-Bera : os retornos são normais?    (esperado: NÃO)
#   ADF         : há raiz unitária?           (esperado: NÃO — série estacionária)
#   KPSS        : a série é estacionária?     (esperado: SIM)
#   ARCH-LM     : há heterocedasticidade?     (esperado: SIM — justifica GARCH)
print("\nTESTES ESTATÍSTICOS:")
jb     = stats.jarque_bera(retorno)
print(f"  Jarque-Bera:    stat={jb[0]:.2f},  p={jb[1]:.4g}")
adf    = adfuller(retorno, autolag='AIC')
print(f"  ADF:            stat={adf[0]:.4f},  p={adf[1]:.4g}")
kp     = kpss(retorno, regression='c', nlags='auto')
print(f"  KPSS:           stat={kp[0]:.4f},  p={kp[1]:.4g}")
arch_t = het_arch(retorno, nlags=10)
print(f"  ARCH-LM(10):    stat={arch_t[0]:.2f},  p={arch_t[1]:.4g}")

# --- FIGURA 03: ACF dos retornos e dos retornos^2 ---
# Retornos^2 apresentam autocorrelação significativa -> confirma efeito ARCH
fig, axes = plt.subplots(2, 1, figsize=(11, 7))
plot_acf(retorno,    lags=40, ax=axes[0],
         title="ACF dos retornos (deve ser ~ ruído branco)")
plot_acf(retorno**2, lags=40, ax=axes[1],
         title="ACF dos retornos² (evidência de ARCH)")
plt.tight_layout()
plt.savefig("figuras/03_acf.png", dpi=130)
plt.close()


# ==============================================================================
# 4. CONSTRUÇÃO DE VARIÁVEIS DUMMY DE INTERVENÇÃO
# ==============================================================================
# Box & Tiao (1975) propõem dois tipos básicos de função de intervenção:
#   • PULSO  : 1 apenas no dia do evento, 0 nos demais (choque transitório)
#   • DEGRAU : 0 antes do evento, 1 do evento em diante (choque permanente)
# ==============================================================================

def dummy_pulso(idx, data):
    """Cria dummy de pulso (efeito transitório no dia do evento)."""
    d = pd.Series(0.0, index=idx)
    data = pd.to_datetime(data)
    if data in d.index:
        d.loc[data] = 1.0
    else:
        # Se o evento caiu em fim de semana/feriado, usa o próximo pregão
        prox_idx = d.index[d.index >= data]
        if len(prox_idx) > 0:
            d.loc[prox_idx[0]] = 1.0
    return d


def dummy_degrau(idx, data):
    """Cria dummy de degrau (efeito permanente após o evento)."""
    return (idx >= pd.to_datetime(data)).astype(float)


# Matriz X com as três intervenções modeladas no relatório
X_interv = pd.DataFrame({
    "I_castello_pulso":  dummy_pulso(retorno.index,  "2021-02-19"),
    "I_lula_degrau":     dummy_degrau(retorno.index, "2023-03-08"),
    "I_prates_pulso":    dummy_pulso(retorno.index,  "2024-05-14"),
}, index=retorno.index)


# ==============================================================================
# 5. MODELAGEM ARMA-GARCH
# ==============================================================================
# Estimam-se três modelos para comparação via critérios AIC/BIC:
#   M1: AR(1)-GARCH(1,1) com inovações t-Student
#   M2: AR(1)-EGARCH(1,1) com inovações t-Student  (capta efeito alavancagem)
#   M3: ARX(1)-EGARCH(1,1)-t com intervenções na média (modelo final)
# Referências: Engle (1982), Bollerslev (1986), Nelson (1991), Morettin (2017).
# ==============================================================================

print("\n" + "=" * 70)
print("5. MODELAGEM ARMA-GARCH")
print("=" * 70)

# Modelo 1 — GARCH(1,1) clássico
m_garch  = arch_model(retorno, mean='AR', lags=1,
                      vol='GARCH', p=1, q=1, dist='t')
res_garch = m_garch.fit(disp='off')

# Modelo 2 — EGARCH(1,1) com termo de assimetria
m_egarch = arch_model(retorno, mean='AR', lags=1,
                      vol='EGARCH', p=1, o=1, q=1, dist='t')
res_egarch = m_egarch.fit(disp='off')

# Modelo 3 — EGARCH com regressores de intervenção na média (FINAL)
m_final = arch_model(retorno, x=X_interv,
                     mean='ARX', lags=1,
                     vol='EGARCH', p=1, o=1, q=1, dist='t')
res_final = m_final.fit(disp='off')

# Tabela comparativa
comp = pd.DataFrame({
    "Modelo": ["GARCH(1,1)-t", "EGARCH(1,1)-t", "EGARCH(1,1)-t + Interv."],
    "AIC":    [res_garch.aic, res_egarch.aic, res_final.aic],
    "BIC":    [res_garch.bic, res_egarch.bic, res_final.bic],
    "LogLik": [res_garch.loglikelihood, res_egarch.loglikelihood,
               res_final.loglikelihood],
})
print("\nCOMPARAÇÃO DE MODELOS:")
print(comp.to_string(index=False))
comp.to_csv("resultados/comparacao_modelos.csv", index=False)

print("\n" + "-" * 70)
print("MODELO FINAL: EGARCH(1,1)-t com intervenções")
print("-" * 70)
print(res_final.summary())

# Salva o sumário do modelo final em arquivo TXT
with open("resultados/sumario_modelo_final.txt", "w", encoding="utf-8") as f:
    f.write(str(res_final.summary()))


# ==============================================================================
# 6. DIAGNÓSTICO DOS RESÍDUOS
# ==============================================================================
# Após estimar o modelo, verifica-se se os resíduos padronizados se comportam
# como ruído branco (sem autocorrelação) e se sua variância já não exibe
# heterocedasticidade remanescente.
# ==============================================================================

print("\n" + "=" * 70)
print("6. DIAGNÓSTICO DOS RESÍDUOS")
print("=" * 70)

res_pad = res_final.std_resid # resíduos padronizados

# Teste de Ljung-Box (1978):
#   H0: ausência de autocorrelação até o lag k
lb_r  = acorr_ljungbox(res_pad,    lags=[10, 20], return_df=True)
lb_r2 = acorr_ljungbox(res_pad**2, lags=[10, 20], return_df=True)
print("\nLjung-Box resíduos padronizados:")
print(lb_r)
print("\nLjung-Box resíduos padronizados²:")
print(lb_r2)
lb_r.to_csv("resultados/ljungbox_residuos.csv")
lb_r2.to_csv("resultados/ljungbox_residuos2.csv")

# --- FIGURA 04: painel de diagnóstico ---
fig, axes = plt.subplots(2, 2, figsize=(13, 8))
axes[0, 0].plot(res_pad, linewidth=0.5)
axes[0, 0].set_title("Resíduos padronizados")
plot_acf(res_pad,    lags=30, ax=axes[0, 1])
axes[0, 1].set_title("ACF resíduos padronizados")
plot_acf(res_pad**2, lags=30, ax=axes[1, 0])
axes[1, 0].set_title("ACF resíduos padronizados²")
stats.probplot(res_pad, dist=stats.t,
               sparams=(res_final.params['nu'],), plot=axes[1, 1])
axes[1, 1].set_title("QQ-plot vs t-Student")
plt.tight_layout()
plt.savefig("figuras/04_diagnostico.png", dpi=130)
plt.close()

# --- FIGURA 05: volatilidade condicional estimada ----------------------------
vol = res_final.conditional_volatility
plt.figure(figsize=(14, 5))
plt.plot(vol, color='darkred', linewidth=0.7)
plt.title("Volatilidade Condicional Estimada (EGARCH-t)")
plt.ylabel("Desvio condicional (%)")
for nome, data in eventos.items():
    plt.axvline(pd.to_datetime(data), color='black',
                linestyle='--', alpha=0.5, linewidth=0.8)
plt.tight_layout()
plt.savefig("figuras/05_volatilidade.png", dpi=130)
plt.close()


# ==============================================================================
# 7. VALUE-AT-RISK (VaR) E BACKTESTING
# ==============================================================================
# VaR paramétrico baseado no modelo EGARCH-t:
#   VaR_t(α) = -(μ_t + q_α(ν) · σ_t)
# onde q_α(ν) é o quantil-alpha da t-Student padronizada com ν graus de liberdade.
# Backtesting via teste de Kupiec (1995).
# ==============================================================================

print("\n" + "=" * 70)
print("7. VALUE-AT-RISK E BACKTESTING")
print("=" * 70)

mu = res_final.params.get('Const', 0.0) # constante da média condicional
nu = res_final.params['nu'] # graus de liberdade da t

def var_quantil(alpha, nu):
    """Quantil-α da t-Student padronizada (variância 1)."""
    return stats.t.ppf(alpha, df=nu) * np.sqrt((nu - 2) / nu)

q_95 = var_quantil(0.05, nu)
q_99 = var_quantil(0.01, nu)

VaR_95 = -(mu + q_95 * vol)
VaR_99 = -(mu + q_99 * vol)

# Contagem de violações (retornos abaixo do limite estimado)
viol_95 = (retorno < -VaR_95).sum()
viol_99 = (retorno < -VaR_99).sum()
n = len(retorno)

print(f"\nVaR 95%: violações = {viol_95}/{n} ({viol_95/n:.2%}, esperado 5%)")
print(f"VaR 99%: violações = {viol_99}/{n} ({viol_99/n:.2%}, esperado 1%)")


def kupiec_test(violacoes, n, alpha):
    """Teste de razão de verossimilhança de Kupiec (1995)."""
    if violacoes == 0:
        return np.nan, np.nan
    p_hat = violacoes / n
    LR = -2 * (np.log(((1 - alpha) ** (n - violacoes)) * (alpha ** violacoes)) -
               np.log(((1 - p_hat) ** (n - violacoes)) * (p_hat ** violacoes)))
    pv = 1 - stats.chi2.cdf(LR, df=1)
    return LR, pv


LR95, pv95 = kupiec_test(viol_95, n, 0.05)
LR99, pv99 = kupiec_test(viol_99, n, 0.01)
print(f"\nKupiec 95%: LR={LR95:.3f}, p={pv95:.4f}")
print(f"Kupiec 99%: LR={LR99:.3f}, p={pv99:.4f}")

resultados_var = pd.DataFrame({
    "Nível":      ["95%", "99%"],
    "Violações":  [viol_95, viol_99],
    "Taxa obs.":  [viol_95 / n, viol_99 / n],
    "Taxa esp.":  [0.05, 0.01],
    "Kupiec LR":  [LR95, LR99],
    "p-valor":    [pv95, pv99],
})
resultados_var.to_csv("resultados/var_backtesting.csv", index=False)

# --- FIGURA 06: VaR vs retornos ---
fig, ax = plt.subplots(figsize=(14, 6))
ax.plot(retorno, color='steelblue', alpha=0.5, linewidth=0.5, label='Retornos')
ax.plot(-VaR_95, color='orange', linewidth=1, label='-VaR 95%')
ax.plot(-VaR_99, color='red',    linewidth=1, label='-VaR 99%')
mask99 = retorno < -VaR_99
ax.scatter(retorno.index[mask99], retorno[mask99],
           color='red', s=15, label='Violações 99%', zorder=5)
ax.set_title("Value-at-Risk 1-dia — PETR4")
ax.legend()
plt.tight_layout()
plt.savefig("figuras/06_var.png", dpi=130)
plt.close()


# ==============================================================================
# 8. SALVAR RESUMO GERAL EM ARQUIVO TXT
# ==============================================================================

with open("resultados/resumo_geral.txt", "w", encoding="utf-8") as f:
    f.write("RESUMO GERAL DO PROJETO 2 — PETR4\n")
    f.write("=" * 70 + "\n\n")
    f.write(f"Período: {preco.index.min().date()} a {preco.index.max().date()}\n")
    f.write(f"N de retornos: {len(retorno)}\n\n")
    f.write("ESTATÍSTICAS DESCRITIVAS:\n")
    f.write(desc.round(4).to_string() + "\n\n")
    f.write(f"Jarque-Bera:  stat={jb[0]:.2f},  p={jb[1]:.4g}\n")
    f.write(f"ADF:          stat={adf[0]:.4f}, p={adf[1]:.4g}\n")
    f.write(f"KPSS:         stat={kp[0]:.4f}, p={kp[1]:.4g}\n")
    f.write(f"ARCH-LM(10):  stat={arch_t[0]:.2f},  p={arch_t[1]:.4g}\n\n")
    f.write("COMPARAÇÃO DE MODELOS:\n")
    f.write(comp.to_string(index=False) + "\n\n")
    f.write("VAR / BACKTESTING:\n")
    f.write(resultados_var.to_string(index=False) + "\n")
